// Tetromino definitions in the Super Rotation System.
//
// Each piece is given once as its spawn-state matrix inside the SRS bounding
// box (4x4 for I, 3x3 for everything else). The four rotation states are
// generated by rotating that matrix clockwise, which is exactly how SRS
// defines them: rotation about the centre of the box, not about a cell.
// Generating rather than hand-typing means the tables cannot disagree with
// each other.
//
// Coordinates are [x, y] with y growing DOWN, matching the board grid.

const PIECES = (() => {
  const SHAPES = {
    I: ['....', 'IIII', '....', '....'],
    J: ['J..', 'JJJ', '...'],
    L: ['..L', 'LLL', '...'],
    O: ['.OO', '.OO', '...'],
    S: ['.SS', 'SS.', '...'],
    T: ['.T.', 'TTT', '...'],
    Z: ['ZZ.', '.ZZ', '...'],
  };

  const COLORS = {
    I: '#3fd3e8', J: '#4c6fe8', L: '#f0a030', O: '#f3d33a',
    S: '#5ad25a', T: '#b060e0', Z: '#e8504c',
  };

  // Clockwise rotation of a square matrix of strings: new[y][x] = old[n-1-x][y].
  function rotateCW(m) {
    const n = m.length;
    return Array.from({ length: n }, (_, y) =>
      Array.from({ length: n }, (_, x) => m[n - 1 - x][y]).join(''));
  }

  function toCells(m) {
    const cells = [];
    m.forEach((row, y) => [...row].forEach((ch, x) => { if (ch !== '.') cells.push([x, y]); }));
    return cells;
  }

  // STATES[type][rot] -> array of [x, y] offsets from the piece origin.
  const STATES = {};
  for (const [type, spawn] of Object.entries(SHAPES)) {
    const states = [];
    let m = spawn;
    for (let r = 0; r < 4; r++) { states.push(toCells(m)); m = rotateCW(m); }
    // O is symmetric, but rotating its 3x3 box would walk it around the
    // box. SRS fixes that with offset data; we just pin all four states.
    STATES[type] = type === 'O' ? [states[0], states[0], states[0], states[0]] : states;
  }

  // SRS wall-kick offsets, keyed "from>to" with states 0=spawn 1=R 2=180 3=L.
  // The published tables use y-up; these are already flipped to y-down.
  const KICKS_JLSTZ = {
    '0>1': [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],
    '1>0': [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],
    '1>2': [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],
    '2>1': [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],
    '2>3': [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],
    '3>2': [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],
    '3>0': [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],
    '0>3': [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],
  };
  const KICKS_I = {
    '0>1': [[0, 0], [-2, 0], [1, 0], [-2, 1], [1, -2]],
    '1>0': [[0, 0], [2, 0], [-1, 0], [2, -1], [-1, 2]],
    '1>2': [[0, 0], [-1, 0], [2, 0], [-1, -2], [2, 1]],
    '2>1': [[0, 0], [1, 0], [-2, 0], [1, 2], [-2, -1]],
    '2>3': [[0, 0], [2, 0], [-1, 0], [2, -1], [-1, 2]],
    '3>2': [[0, 0], [-2, 0], [1, 0], [-2, 1], [1, -2]],
    '3>0': [[0, 0], [1, 0], [-2, 0], [1, 2], [-2, -1]],
    '0>3': [[0, 0], [-1, 0], [2, 0], [-1, -2], [2, 1]],
  };
  const KICKS_O = { '0>1': [[0, 0]], '1>0': [[0, 0]], '1>2': [[0, 0]], '2>1': [[0, 0]],
                    '2>3': [[0, 0]], '3>2': [[0, 0]], '3>0': [[0, 0]], '0>3': [[0, 0]] };

  function kicks(type, from, to) {
    const table = type === 'I' ? KICKS_I : type === 'O' ? KICKS_O : KICKS_JLSTZ;
    return table[`${from}>${to}`];
  }

  return {
    TYPES: Object.keys(SHAPES),
    COLORS,
    STATES,
    kicks,
    cells: (type, rot) => STATES[type][rot & 3],
    size: (type) => SHAPES[type].length,
  };
})();

if (typeof module !== 'undefined') module.exports = PIECES;
