// Tetris — agent-1
//
// One file, one closure. Read top to bottom:
//   1. tables     piece shapes (SRS), kick tables, colours
//   2. board      flat Uint8Array, 10 x 40, bottom 20 rows visible
//   3. pieces     spawn, collision, movement primitives
//   4. loop       requestAnimationFrame with dt accumulators
//   5. render     canvas 2D, whole board redrawn every frame
(() => {
'use strict';

// ---------------------------------------------------------------- 1. tables

const W = 10;          // columns
const H = 40;          // rows in the array
const VIS = 20;        // rows actually drawn (the bottom VIS of H)
const HIDDEN = H - VIS;
const CELL = 30;       // css px per cell

// Spawn orientation of each piece as [x, y] cells inside its SRS bounding
// box (3x3 for J L S T Z, 4x4 for I, O is 3x3 with cells offset right).
// The other three orientations are generated by rotating inside that box,
// which is exactly what SRS defines, so kicks below line up with these.
const SPAWN = {
  I: { n: 4, cells: [[0, 1], [1, 1], [2, 1], [3, 1]] },
  O: { n: 3, cells: [[1, 0], [2, 0], [1, 1], [2, 1]] },
  T: { n: 3, cells: [[1, 0], [0, 1], [1, 1], [2, 1]] },
  S: { n: 3, cells: [[1, 0], [2, 0], [0, 1], [1, 1]] },
  Z: { n: 3, cells: [[0, 0], [1, 0], [1, 1], [2, 1]] },
  J: { n: 3, cells: [[0, 0], [0, 1], [1, 1], [2, 1]] },
  L: { n: 3, cells: [[2, 0], [0, 1], [1, 1], [2, 1]] },
};

const NAMES = ['I', 'O', 'T', 'S', 'Z', 'J', 'L']; // id = index + 1

// PIECES[id] = { n, rot: [cells0, cellsR, cells2, cellsL] }
// Rotating a cell clockwise inside an n x n box: (x, y) -> (n-1-y, x).
const PIECES = [null];
for (const name of NAMES) {
  const { n, cells } = SPAWN[name];
  const rot = [cells];
  for (let r = 1; r < 4; r++) {
    rot.push(rot[r - 1].map(([x, y]) => [n - 1 - y, x]));
  }
  // O rotates in place: every orientation is the spawn shape.
  if (name === 'O') rot.fill(cells);
  PIECES.push({ name, n, rot });
}

// SRS wall kick tables, from the Tetris Guideline, with y flipped so that
// +y is DOWN to match the board array. KICKS.X[from][dir] is the list of
// [dx, dy] offsets to try in order; dir 0 = clockwise, 1 = counter-clockwise.
// States: 0 spawn, 1 right (R), 2 upside down, 3 left (L).
const KICKS = {
  JLSTZ: [
    [[[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],   // 0 -> R
     [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]]],      // 0 -> L
    [[[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],      // R -> 2
     [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]]],     // R -> 0
    [[[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],       // 2 -> L
     [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]]],   // 2 -> R
    [[[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],   // L -> 0
     [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]]],  // L -> 2
  ],
  I: [
    [[[0, 0], [-2, 0], [1, 0], [-2, 1], [1, -2]],     // 0 -> R
     [[0, 0], [-1, 0], [2, 0], [-1, -2], [2, 1]]],    // 0 -> L
    [[[0, 0], [-1, 0], [2, 0], [-1, -2], [2, 1]],     // R -> 2
     [[0, 0], [2, 0], [-1, 0], [2, -1], [-1, 2]]],    // R -> 0
    [[[0, 0], [2, 0], [-1, 0], [2, -1], [-1, 2]],     // 2 -> L
     [[0, 0], [1, 0], [-2, 0], [1, 2], [-2, -1]]],    // 2 -> R
    [[[0, 0], [1, 0], [-2, 0], [1, 2], [-2, -1]],     // L -> 0
     [[0, 0], [-2, 0], [1, 0], [-2, 1], [1, -2]]],    // L -> 2
  ],
  O: [[[[0, 0]], [[0, 0]]], [[[0, 0]], [[0, 0]]], [[[0, 0]], [[0, 0]]], [[[0, 0]], [[0, 0]]]],
};
function kicksFor(id) {
  const name = PIECES[id].name;
  return name === 'I' ? KICKS.I : name === 'O' ? KICKS.O : KICKS.JLSTZ;
}

const COLORS = [null, '#3fd5ea', '#f2d23a', '#b163f0', '#5fd75f', '#ee4c4c', '#4d7cf5', '#f29a3a'];

// Guideline gravity: seconds per row at a level.
function gravitySeconds(level) {
  const l = Math.min(level, 20) - 1;
  return Math.pow(0.8 - l * 0.007, l);
}
const LOCK_DELAY = 500; // ms a piece may rest on something before it locks

// ---------------------------------------------------------------- 2. board

const board = new Uint8Array(W * H);
const at = (x, y) => board[y * W + x];

// True if any cell of piece `id` in orientation `r` at (px, py) is out of
// bounds or on a filled cell. y < 0 is out of bounds too; the hidden rows
// exist precisely so nothing legal ever gets there.
function collides(id, r, px, py) {
  for (const [cx, cy] of PIECES[id].rot[r]) {
    const x = px + cx, y = py + cy;
    if (x < 0 || x >= W || y < 0 || y >= H) return true;
    if (board[y * W + x]) return true;
  }
  return false;
}

// ---------------------------------------------------------------- 3. pieces

// 7-bag randomizer: every piece once per bag, so droughts are bounded.
const bag = [];
function nextId() {
  if (bag.length === 0) {
    for (let i = 1; i <= 7; i++) bag.push(i);
    for (let i = bag.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [bag[i], bag[j]] = [bag[j], bag[i]];
    }
  }
  return bag.pop();
}

const state = {
  cur: null,       // { id, r, x, y }
  level: 1,
  over: false,
  gravityAcc: 0,   // ms accumulated toward the next gravity step
  lockAcc: 0,      // ms the piece has been resting
};

function spawn() {
  const id = nextId();
  const n = PIECES[id].n;
  const x = Math.floor((W - n) / 2);   // 3 for 3x3, 3 for 4x4
  const y = HIDDEN - 1;                // bottom row of the box is the top visible row
  if (collides(id, 0, x, y)) {
    state.over = true;
    return;
  }
  state.cur = { id, r: 0, x, y };
  state.gravityAcc = 0;
  state.lockAcc = 0;
}

// Try to shift the current piece. Returns true if it moved.
function shift(dx, dy) {
  const p = state.cur;
  if (collides(p.id, p.r, p.x + dx, p.y + dy)) return false;
  p.x += dx;
  p.y += dy;
  return true;
}

function lock() {
  const p = state.cur;
  let allHidden = true;
  for (const [cx, cy] of PIECES[p.id].rot[p.r]) {
    const y = p.y + cy;
    board[y * W + p.x + cx] = p.id;
    if (y >= HIDDEN) allHidden = false;
  }
  if (allHidden) {          // locked entirely above the visible area: lock out
    state.over = true;
    return;
  }
  spawn();
}

// ---------------------------------------------------------------- 4. loop

let last = performance.now();
function frame(now) {
  // Clamp dt so a backgrounded tab does not dump seconds of gravity at once.
  const dt = Math.min(now - last, 100);
  last = now;
  if (!state.over) update(dt);
  render();
  requestAnimationFrame(frame);
}

function update(dt) {
  const p = state.cur;
  const resting = collides(p.id, p.r, p.x, p.y + 1);

  if (resting) {
    state.lockAcc += dt;
    state.gravityAcc = 0;
    if (state.lockAcc >= LOCK_DELAY) lock();
    return;
  }
  state.lockAcc = 0;

  state.gravityAcc += dt;
  const step = gravitySeconds(state.level) * 1000;
  while (state.gravityAcc >= step && !collides(p.id, p.r, p.x, p.y + 1)) {
    state.gravityAcc -= step;
    p.y++;
  }
}

// ---------------------------------------------------------------- 5. render

const canvas = document.getElementById('board');
const ctx = canvas.getContext('2d');

// Backing store scaled by devicePixelRatio so cell edges are crisp.
function fitCanvas(c, cssW, cssH) {
  const dpr = window.devicePixelRatio || 1;
  c.width = Math.round(cssW * dpr);
  c.height = Math.round(cssH * dpr);
  c.style.width = cssW + 'px';
  c.style.height = cssH + 'px';
  c.getContext('2d').setTransform(dpr, 0, 0, dpr, 0, 0);
}
fitCanvas(canvas, W * CELL, VIS * CELL);

function drawCell(c, x, y, color, size = CELL) {
  const px = x * size, py = y * size;
  c.fillStyle = color;
  c.fillRect(px, py, size, size);
  // bevel: light top-left, dark bottom-right
  c.fillStyle = 'rgba(255,255,255,.25)';
  c.fillRect(px, py, size, 2);
  c.fillRect(px, py, 2, size);
  c.fillStyle = 'rgba(0,0,0,.3)';
  c.fillRect(px, py + size - 2, size, 2);
  c.fillRect(px + size - 2, py, 2, size);
}

function render() {
  ctx.fillStyle = '#0a0c11';
  ctx.fillRect(0, 0, W * CELL, VIS * CELL);

  // grid
  ctx.strokeStyle = 'rgba(255,255,255,.05)';
  ctx.lineWidth = 1;
  ctx.beginPath();
  for (let x = 1; x < W; x++) { ctx.moveTo(x * CELL + .5, 0); ctx.lineTo(x * CELL + .5, VIS * CELL); }
  for (let y = 1; y < VIS; y++) { ctx.moveTo(0, y * CELL + .5); ctx.lineTo(W * CELL, y * CELL + .5); }
  ctx.stroke();

  // settled cells
  for (let y = HIDDEN; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const id = board[y * W + x];
      if (id) drawCell(ctx, x, y - HIDDEN, COLORS[id]);
    }
  }

  // falling piece
  const p = state.cur;
  if (p) {
    for (const [cx, cy] of PIECES[p.id].rot[p.r]) {
      const y = p.y + cy - HIDDEN;
      if (y >= 0) drawCell(ctx, p.x + cx, y, COLORS[p.id]);
    }
  }
}

// ---------------------------------------------------------------- go

spawn();
requestAnimationFrame(frame);

// Debug handle: lets a test harness (or a curious reader) drive the loop.
window.__tetris = { state, board, PIECES, KICKS, collides, frame, W, H, HIDDEN };

})();
