// Tetris — agent-1
//
// One file, one closure. Read top to bottom:
//   1. tables     piece shapes (SRS), kick tables, colours
//   2. board      flat Uint8Array, 10 x 40, bottom 20 rows visible
//   3. pieces     spawn, collision, movement primitives
//   4. loop       requestAnimationFrame with dt accumulators
//   5. render     canvas 2D, whole board redrawn every frame
(() => {
'use strict';

// ---------------------------------------------------------------- 1. tables

const W = 10;          // columns
const H = 40;          // rows in the array
const VIS = 20;        // rows actually drawn (the bottom VIS of H)
const HIDDEN = H - VIS;
const CELL = 30;       // css px per cell

// Spawn orientation of each piece as [x, y] cells inside its SRS bounding
// box (3x3 for J L S T Z, 4x4 for I, O is 3x3 with cells offset right).
// The other three orientations are generated by rotating inside that box,
// which is exactly what SRS defines, so kicks below line up with these.
const SPAWN = {
  I: { n: 4, cells: [[0, 1], [1, 1], [2, 1], [3, 1]] },
  O: { n: 3, cells: [[1, 0], [2, 0], [1, 1], [2, 1]] },
  T: { n: 3, cells: [[1, 0], [0, 1], [1, 1], [2, 1]] },
  S: { n: 3, cells: [[1, 0], [2, 0], [0, 1], [1, 1]] },
  Z: { n: 3, cells: [[0, 0], [1, 0], [1, 1], [2, 1]] },
  J: { n: 3, cells: [[0, 0], [0, 1], [1, 1], [2, 1]] },
  L: { n: 3, cells: [[2, 0], [0, 1], [1, 1], [2, 1]] },
};

const NAMES = ['I', 'O', 'T', 'S', 'Z', 'J', 'L']; // id = index + 1

// PIECES[id] = { n, rot: [cells0, cellsR, cells2, cellsL] }
// Rotating a cell clockwise inside an n x n box: (x, y) -> (n-1-y, x).
const PIECES = [null];
for (const name of NAMES) {
  const { n, cells } = SPAWN[name];
  const rot = [cells];
  for (let r = 1; r < 4; r++) {
    rot.push(rot[r - 1].map(([x, y]) => [n - 1 - y, x]));
  }
  // O rotates in place: every orientation is the spawn shape.
  if (name === 'O') rot.fill(cells);
  PIECES.push({ name, n, rot });
}

// SRS wall kick tables, from the Tetris Guideline, with y flipped so that
// +y is DOWN to match the board array. KICKS.X[from][dir] is the list of
// [dx, dy] offsets to try in order; dir 0 = clockwise, 1 = counter-clockwise.
// States: 0 spawn, 1 right (R), 2 upside down, 3 left (L).
const KICKS = {
  JLSTZ: [
    [[[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]],   // 0 -> R
     [[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]]],      // 0 -> L
    [[[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]],      // R -> 2
     [[0, 0], [1, 0], [1, 1], [0, -2], [1, -2]]],     // R -> 0
    [[[0, 0], [1, 0], [1, -1], [0, 2], [1, 2]],       // 2 -> L
     [[0, 0], [-1, 0], [-1, -1], [0, 2], [-1, 2]]],   // 2 -> R
    [[[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]],   // L -> 0
     [[0, 0], [-1, 0], [-1, 1], [0, -2], [-1, -2]]],  // L -> 2
  ],
  I: [
    [[[0, 0], [-2, 0], [1, 0], [-2, 1], [1, -2]],     // 0 -> R
     [[0, 0], [-1, 0], [2, 0], [-1, -2], [2, 1]]],    // 0 -> L
    [[[0, 0], [-1, 0], [2, 0], [-1, -2], [2, 1]],     // R -> 2
     [[0, 0], [2, 0], [-1, 0], [2, -1], [-1, 2]]],    // R -> 0
    [[[0, 0], [2, 0], [-1, 0], [2, -1], [-1, 2]],     // 2 -> L
     [[0, 0], [1, 0], [-2, 0], [1, 2], [-2, -1]]],    // 2 -> R
    [[[0, 0], [1, 0], [-2, 0], [1, 2], [-2, -1]],     // L -> 0
     [[0, 0], [-2, 0], [1, 0], [-2, 1], [1, -2]]],    // L -> 2
  ],
  O: [[[[0, 0]], [[0, 0]]], [[[0, 0]], [[0, 0]]], [[[0, 0]], [[0, 0]]], [[[0, 0]], [[0, 0]]]],
};
function kicksFor(id) {
  const name = PIECES[id].name;
  return name === 'I' ? KICKS.I : name === 'O' ? KICKS.O : KICKS.JLSTZ;
}

const COLORS = [null, '#3fd5ea', '#f2d23a', '#b163f0', '#5fd75f', '#ee4c4c', '#4d7cf5', '#f29a3a'];

// Guideline gravity: seconds per row at a level.
function gravitySeconds(level) {
  const l = Math.min(level, 20) - 1;
  return Math.pow(0.8 - l * 0.007, l);
}
const LOCK_DELAY = 500;   // ms a piece may rest on something before it locks
const LOCK_RESETS = 15;   // shifts/rotations that may restart that timer per piece
const DAS = 150;          // ms a direction is held before it auto-repeats
const ARR = 33;           // ms between auto-repeat shifts
const SOFT_DROP = 20;     // soft drop runs gravity this many times faster
const CLEAR_FLASH = 120;  // ms full rows stay on screen, white, before collapsing
const LINES_PER_LEVEL = 10;

// Guideline scoring, all multiplied by level at award time.
const SCORE = {
  clear:   [0, 100, 300, 500, 800],        // by lines
  tspin:   [400, 800, 1200, 1600],         // T-spin by lines (0..3)
  mini:    [100, 200, 400],                // mini T-spin by lines (0..2)
  perfect: [0, 800, 1200, 1800, 2000],     // perfect clear by lines
  perfectB2B: 3200,                        // back-to-back tetris perfect clear
  combo: 50,                               // x combo count
  soft: 1, hard: 2,                        // per row dropped
};
const T_ID = NAMES.indexOf('T') + 1;

// ---------------------------------------------------------------- 2. board

const board = new Uint8Array(W * H);

// True if any cell of piece `id` in orientation `r` at (px, py) is out of
// bounds or on a filled cell. y < 0 is out of bounds too; the hidden rows
// exist precisely so nothing legal ever gets there.
function collides(id, r, px, py) {
  for (const [cx, cy] of PIECES[id].rot[r]) {
    const x = px + cx, y = py + cy;
    if (x < 0 || x >= W || y < 0 || y >= H) return true;
    if (board[y * W + x]) return true;
  }
  return false;
}

// y indices of completely filled rows, ascending.
function fullRows() {
  const rows = [];
  for (let y = 0; y < H; y++) {
    let full = true;
    for (let x = 0; x < W; x++) if (!board[y * W + x]) { full = false; break; }
    if (full) rows.push(y);
  }
  return rows;
}

// Remove rows (ascending). copyWithin slides everything above row y down by
// one and the top row is blanked; rows below y keep their index, so
// ascending order stays valid as we go. No allocation.
function removeRows(rows) {
  for (const y of rows) {
    board.copyWithin(W, 0, y * W);
    board.fill(0, 0, W);
  }
}

function boardEmpty() {
  for (let i = 0; i < board.length; i++) if (board[i]) return false;
  return true;
}

// ---------------------------------------------------------------- 3. pieces

// 7-bag randomizer: every piece once per bag, so droughts are bounded.
let bag = [];
function nextId() {
  if (bag.length === 0) {
    for (let i = 1; i <= 7; i++) bag.push(i);
    for (let i = bag.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [bag[i], bag[j]] = [bag[j], bag[i]];
    }
  }
  return bag.pop();
}

const state = {
  cur: null,        // { id, r, x, y, lowestY, spun, kick }
  score: 0,
  lines: 0,
  level: 1,
  combo: -1,        // consecutive clearing locks; -1 = none in progress
  b2b: false,       // last clear was a tetris or T-spin
  over: false,
  clearing: null,   // { rows, acc } while full rows flash; no piece exists then
  event: '',        // HUD line naming the last clear
  gravityAcc: 0,    // ms accumulated toward the next gravity step
  lockAcc: 0,       // ms the piece has been resting
  lockResets: 0,    // lock-delay restarts used at the current lowest row
};

// Held horizontal directions, oldest first. The newest press wins; releasing
// it falls back to whatever is still held. (Taken from agent-3's
// "release resumes the other direction"; the stack replaces their
// left/right/dasDir triple.)
const input = {
  held: [],         // e.g. [-1, 1] means left was pressed, then right
  dasAcc: 0,        // ms toward the next auto-shift
  charged: false,   // DAS has elapsed; now repeating every ARR
  soft: false,      // down is held
};
const activeDir = () => input.held.length ? input.held[input.held.length - 1] : 0;

function reset() {
  board.fill(0);
  bag = [];
  Object.assign(state, {
    cur: null, score: 0, lines: 0, level: 1, combo: -1, b2b: false,
    over: false, clearing: null, event: '', gravityAcc: 0, lockAcc: 0, lockResets: 0,
  });
  spawn();
}

function spawn() {
  const id = nextId();
  const n = PIECES[id].n;
  const x = Math.floor((W - n) / 2);   // 3 for both 3x3 and 4x4 boxes
  // Bottom row of the box on the top visible row; if that is blocked try one
  // row higher (agent-3's fallback) before topping out.
  for (const y of [HIDDEN - 1, HIDDEN - 2]) {
    if (!collides(id, 0, x, y)) {
      state.cur = { id, r: 0, x, y, lowestY: y, spun: false, kick: -1 };
      state.gravityAcc = 0;
      state.lockAcc = 0;
      state.lockResets = 0;
      return;
    }
  }
  state.cur = { id, r: 0, x, y: HIDDEN - 2, lowestY: 0, spun: false, kick: -1 };
  state.over = true;   // block out
}

const grounded = () => { const p = state.cur; return collides(p.id, p.r, p.x, p.y + 1); };

// A shift or rotation while resting restarts the lock timer, LOCK_RESETS
// times at most, so a piece cannot be stalled forever. The budget refills
// when the piece reaches a new lowest row (Guideline move reset, via agent-2).
function noteMoved() {
  if (grounded() && state.lockResets < LOCK_RESETS) {
    state.lockAcc = 0;
    state.lockResets++;
  }
}

// Try to shift the current piece. Returns true if it moved. Any successful
// shift means the last action was not a rotation, which matters for T-spins.
function shift(dx, dy) {
  const p = state.cur;
  if (collides(p.id, p.r, p.x + dx, p.y + dy)) return false;
  p.x += dx;
  p.y += dy;
  p.spun = false;
  if (p.y > p.lowestY) {
    p.lowestY = p.y;
    state.lockResets = 0;
  }
  return true;
}

function move(dx) {
  if (state.over || !state.cur) return;
  if (shift(dx, 0)) noteMoved();
}

// dir: 0 clockwise, 1 counter-clockwise. Walk the SRS kick list for this
// (from, dir) pair; the first offset that fits wins. Records which kick was
// used because the fifth one upgrades a mini T-spin to a full one.
function rotate(dir) {
  if (state.over || !state.cur) return false;
  const p = state.cur;
  const to = (p.r + (dir === 0 ? 1 : 3)) % 4;
  const kicks = kicksFor(p.id)[p.r][dir];
  for (let i = 0; i < kicks.length; i++) {
    const [kx, ky] = kicks[i];
    if (!collides(p.id, to, p.x + kx, p.y + ky)) {
      p.r = to;
      p.x += kx;
      p.y += ky;
      p.spun = true;
      p.kick = i;
      if (p.y > p.lowestY) { p.lowestY = p.y; state.lockResets = 0; }
      noteMoved();
      return true;
    }
  }
  return false;
}

function hardDrop() {
  if (state.over || !state.cur) return;
  let rows = 0;
  while (shift(0, 1)) rows++;
  state.score += rows * SCORE.hard;
  lock();
}

// 3-corner rule (from agent-5): a T whose last action was a rotation, with at
// least three of the four diagonals around its centre solid, was spun in.
// It is a full T-spin if both corners on the side it points to are solid, or
// if it arrived by the fifth kick; otherwise a mini. Returns null/'mini'/'full'.
function tspinKind(p) {
  if (p.id !== T_ID || !p.spun) return null;
  const solid = (x, y) => x < 0 || x >= W || y < 0 || y >= H || board[y * W + x] !== 0;
  const cx = p.x + 1, cy = p.y + 1;             // T's centre is the middle of its 3x3 box
  const tl = solid(cx - 1, cy - 1), tr = solid(cx + 1, cy - 1);
  const bl = solid(cx - 1, cy + 1), br = solid(cx + 1, cy + 1);
  if (tl + tr + bl + br < 3) return null;
  const front = [[tl, tr], [tr, br], [bl, br], [tl, bl]][p.r];   // corners the T points at
  return (front[0] && front[1]) || p.kick === 4 ? 'full' : 'mini';
}

// Points for a lock that cleared n lines with the given spin kind.
function award(n, spin, perfect) {
  let pts, label;
  if (spin === 'full')      { pts = SCORE.tspin[n]; label = 'T-Spin'; }
  else if (spin === 'mini') { pts = SCORE.mini[Math.min(n, 2)]; label = 'Mini T-Spin'; }
  else                      { pts = SCORE.clear[n]; label = ''; }
  if (n > 0) label = (label ? label + ' ' : '') + ['', 'Single', 'Double', 'Triple', 'Tetris'][n];

  const hard = n === 4 || spin !== null;        // clears that keep the B2B chain alive
  if (n > 0) {
    if (hard && state.b2b) { pts = Math.floor(pts * 1.5); label = 'B2B ' + label; }
    if (perfect) {
      pts += (hard && state.b2b && n === 4) ? SCORE.perfectB2B : SCORE.perfect[n];
      label = 'Perfect Clear ' + label;
    }
    state.b2b = hard;
    state.combo++;
    if (state.combo > 0) { pts += SCORE.combo * state.combo; label += '  x' + (state.combo + 1); }
    state.lines += n;
    state.level = 1 + Math.floor(state.lines / LINES_PER_LEVEL);
  } else {
    state.combo = -1;
  }
  state.score += pts * state.level;
  if (label) state.event = label;
}

function lock() {
  const p = state.cur;
  const spin = tspinKind(p);              // before stamping: the T's own cells are not corners
  let allHidden = true;
  for (const [cx, cy] of PIECES[p.id].rot[p.r]) {
    const y = p.y + cy;
    board[y * W + p.x + cx] = p.id;
    if (y >= HIDDEN) allHidden = false;
  }
  state.cur = null;
  if (allHidden) { state.over = true; return; }   // lock out

  const rows = fullRows();
  if (rows.length === 0) {
    award(0, spin, false);
    spawn();
    return;
  }
  // Decide perfect clear now: after removal the board is empty iff every
  // filled cell was on a full row.
  let filled = 0;
  for (let i = 0; i < board.length; i++) if (board[i]) filled++;
  award(rows.length, spin, filled === rows.length * W);
  state.clearing = { rows, acc: 0 };      // rows flash, then finishClear() collapses them
}

function finishClear() {
  removeRows(state.clearing.rows);
  state.clearing = null;
  spawn();
}

// ---------------------------------------------------------------- 4. loop

let last = performance.now();
function frame(now) {
  // Clamp dt so a backgrounded tab does not dump seconds of gravity at once.
  const dt = Math.min(now - last, 100);
  last = now;
  update(dt);
  render();
  requestAnimationFrame(frame);
}

// Auto-shift: the first shift happens on keydown; holding waits DAS, then
// shifts every ARR. Timers run on the frame clock, not the OS key repeat.
function updateInput(dt) {
  const dir = activeDir();
  if (dir === 0) return;
  input.dasAcc += dt;
  const threshold = input.charged ? ARR : DAS;
  while (input.dasAcc >= threshold) {
    input.dasAcc -= threshold;
    input.charged = true;
    move(dir);
  }
}

function update(dt) {
  if (state.over) return;

  if (state.clearing) {
    state.clearing.acc += dt;
    if (state.clearing.acc >= CLEAR_FLASH) finishClear();
    return;
  }

  updateInput(dt);
  if (state.over || !state.cur) return;

  let step = gravitySeconds(state.level) * 1000;
  if (input.soft) step /= SOFT_DROP;

  if (grounded()) {
    state.lockAcc += dt;
    state.gravityAcc = 0;
    if (state.lockAcc >= LOCK_DELAY) lock();
    return;
  }
  state.lockAcc = 0;

  state.gravityAcc += dt;
  while (state.gravityAcc >= step && shift(0, 1)) {
    state.gravityAcc -= step;
    if (input.soft) state.score += SCORE.soft;
  }
}

// ---------------------------------------------------------------- input

function startShift(dir) {
  input.held = input.held.filter(d => d !== dir);
  input.held.push(dir);
  input.dasAcc = 0;
  input.charged = false;
  move(dir);
}

function stopShift(dir) {
  const wasActive = activeDir() === dir;
  input.held = input.held.filter(d => d !== dir);
  if (wasActive && input.held.length) {
    // fall back to the older direction with a fresh DAS
    input.dasAcc = 0;
    input.charged = false;
  }
}

function onKeyDown(e) {
  if (e.repeat) return;
  switch (e.code) {
    case 'ArrowLeft':  startShift(-1); break;
    case 'ArrowRight': startShift(1); break;
    case 'ArrowDown':  input.soft = true; break;
    case 'ArrowUp': case 'KeyX': rotate(0); break;
    case 'KeyZ': case 'ControlLeft': rotate(1); break;
    case 'Space': hardDrop(); break;
    case 'KeyR': reset(); break;
    case 'Enter': if (state.over) reset(); break;
    default: return;
  }
  e.preventDefault();
}

function onKeyUp(e) {
  switch (e.code) {
    case 'ArrowLeft':  stopShift(-1); break;
    case 'ArrowRight': stopShift(1); break;
    case 'ArrowDown':  input.soft = false; break;
    default: return;
  }
  e.preventDefault();
}

// Losing focus drops every held key so nothing auto-repeats into a wall.
function releaseAll() {
  input.held = [];
  input.soft = false;
}

window.addEventListener('keydown', onKeyDown);
window.addEventListener('keyup', onKeyUp);
window.addEventListener('blur', releaseAll);

// ---------------------------------------------------------------- 5. render

const canvas = document.getElementById('board');
const ctx = canvas.getContext('2d');
const hud = {
  score: document.getElementById('score'),
  level: document.getElementById('level'),
  lines: document.getElementById('lines'),
  event: document.getElementById('event'),
  overlay: document.getElementById('overlay'),
  overlayTitle: document.getElementById('overlay-title'),
  overlayText: document.getElementById('overlay-text'),
};

// Backing store scaled by devicePixelRatio so cell edges are crisp.
function fitCanvas(c, cssW, cssH) {
  const dpr = window.devicePixelRatio || 1;
  c.width = Math.round(cssW * dpr);
  c.height = Math.round(cssH * dpr);
  c.style.width = cssW + 'px';
  c.style.height = cssH + 'px';
  c.getContext('2d').setTransform(dpr, 0, 0, dpr, 0, 0);
}
fitCanvas(canvas, W * CELL, VIS * CELL);

function drawCell(c, x, y, color, size = CELL) {
  const px = x * size, py = y * size;
  c.fillStyle = color;
  c.fillRect(px, py, size, size);
  // bevel: light top-left, dark bottom-right
  c.fillStyle = 'rgba(255,255,255,.25)';
  c.fillRect(px, py, size, 2);
  c.fillRect(px, py, 2, size);
  c.fillStyle = 'rgba(0,0,0,.3)';
  c.fillRect(px, py + size - 2, size, 2);
  c.fillRect(px + size - 2, py, 2, size);
}

function renderBoard() {
  ctx.fillStyle = '#0a0c11';
  ctx.fillRect(0, 0, W * CELL, VIS * CELL);

  // grid
  ctx.strokeStyle = 'rgba(255,255,255,.05)';
  ctx.lineWidth = 1;
  ctx.beginPath();
  for (let x = 1; x < W; x++) { ctx.moveTo(x * CELL + .5, 0); ctx.lineTo(x * CELL + .5, VIS * CELL); }
  for (let y = 1; y < VIS; y++) { ctx.moveTo(0, y * CELL + .5); ctx.lineTo(W * CELL, y * CELL + .5); }
  ctx.stroke();

  // settled cells; rows mid-clear are white so the clear reads as an event
  const flashing = state.clearing ? new Set(state.clearing.rows) : null;
  for (let y = HIDDEN; y < H; y++) {
    const white = flashing && flashing.has(y);
    for (let x = 0; x < W; x++) {
      const id = board[y * W + x];
      if (id) drawCell(ctx, x, y - HIDDEN, white ? '#ffffff' : COLORS[id]);
    }
  }

  // falling piece
  const p = state.cur;
  if (p && !state.over) {
    for (const [cx, cy] of PIECES[p.id].rot[p.r]) {
      const y = p.y + cy - HIDDEN;
      if (y >= 0) drawCell(ctx, p.x + cx, y, COLORS[p.id]);
    }
  }
}

// DOM writes only when a value changes (from agent-3); textContent every
// frame is wasted layout work.
const shown = { score: -1, level: -1, lines: -1, event: null, overlay: null };
function renderHud() {
  if (shown.score !== state.score) hud.score.textContent = shown.score = state.score;
  if (shown.level !== state.level) hud.level.textContent = shown.level = state.level;
  if (shown.lines !== state.lines) hud.lines.textContent = shown.lines = state.lines;
  if (shown.event !== state.event) hud.event.textContent = shown.event = state.event;

  const overlay = state.over ? 'over' : null;
  if (shown.overlay !== overlay) {
    shown.overlay = overlay;
    hud.overlay.classList.toggle('hidden', overlay === null);
    if (overlay === 'over') {
      hud.overlayTitle.textContent = 'Game over';
      hud.overlayText.textContent = 'Press R to restart';
    }
  }
}

function render() {
  renderBoard();
  renderHud();
}

// ---------------------------------------------------------------- go

spawn();
requestAnimationFrame(frame);

// Debug handle: lets a test harness (or a curious reader) drive the loop.
window.__tetris = {
  state, input, board, PIECES, KICKS, SCORE, collides, frame, move, rotate, hardDrop,
  lock, reset, tspinKind, fullRows, onKeyDown, onKeyUp, W, H, HIDDEN,
};

})();
